from _typeshed import ReadableBuffer

def b64encode(s: ReadableBuffer, altchars: ReadableBuffer | None = None) -> bytes: ...
def b64decode(
    s: str | ReadableBuffer,
    altchars: str | ReadableBuffer | None = None,
    validate: bool = False,
) -> bytes: ...
def murmur3_32(s: ReadableBuffer, seed: int = 0) -> int: ...
def murmur3_x86_128_digest(s: ReadableBuffer, seed: int = 0) -> bytes: ...
def murmur3_x64_128_digest(s: ReadableBuffer, seed: int = 0) -> bytes: ...

class murmur3_x86_32:
    def __init__(self, data: ReadableBuffer | None = None, seed: int = 0) -> None: ...
    def update(self, data: ReadableBuffer) -> None: ...
    def digest(self) -> bytes: ...
    def hexdigest(self) -> str: ...
    def copy(self) -> murmur3_x86_32: ...
    @property
    def digest_size(self) -> int: ...
    @property
    def block_size(self) -> int: ...
    @property
    def name(self) -> str: ...

class murmur3_x86_128:
    def __init__(self, data: ReadableBuffer | None = None, seed: int = 0) -> None: ...
    def update(self, data: ReadableBuffer) -> None: ...
    def digest(self) -> bytes: ...
    def hexdigest(self) -> str: ...
    def copy(self) -> murmur3_x86_128: ...
    @property
    def digest_size(self) -> int: ...
    @property
    def block_size(self) -> int: ...
    @property
    def name(self) -> str: ...

class murmur3_x64_128:
    def __init__(self, data: ReadableBuffer | None = None, seed: int = 0) -> None: ...
    def update(self, data: ReadableBuffer) -> None: ...
    def digest(self) -> bytes: ...
    def hexdigest(self) -> str: ...
    def copy(self) -> murmur3_x64_128: ...
    @property
    def digest_size(self) -> int: ...
    @property
    def block_size(self) -> int: ...
    @property
    def name(self) -> str: ...
