from _typeshed import ReadableBuffer

def b64encode(s: ReadableBuffer, altchars: ReadableBuffer | None = None) -> bytes: ...
def b64decode(
    s: str | ReadableBuffer,
    altchars: str | ReadableBuffer | None = None,
    validate: bool = False,
) -> bytes: ...
def murmur3_32(s: ReadableBuffer, seed: int = 0) -> int: ...
def murmur3_x86_128_digest(s: ReadableBuffer, seed: int = 0) -> bytes: ...
def murmur3_x64_128_digest(s: ReadableBuffer, seed: int = 0) -> bytes: ...
