from _typeshed import ReadableBuffer

def b64encode(s: ReadableBuffer, altchars: ReadableBuffer | None = None) -> bytes: ...
def b64encode_into(s: ReadableBuffer, output: bytearray, altchars: ReadableBuffer | None = None) -> int: ...
def b64decode(
    s: str | ReadableBuffer,
    altchars: str | ReadableBuffer | None = None,
    validate: bool = False,
) -> bytes: ...
def b64decode_into(
    s: str | ReadableBuffer,
    output: bytearray,
    altchars: str | ReadableBuffer | None = None,
    validate: bool = False,
) -> int: ...
def standard_b64encode(s: ReadableBuffer) -> bytes: ...
def standard_b64encode_into(s: ReadableBuffer, output: bytearray) -> int: ...
def standard_b64decode(s: str | ReadableBuffer) -> bytes: ...
def standard_b64decode_into(s: str | ReadableBuffer, output: bytearray) -> int: ...
def urlsafe_b64encode(s: ReadableBuffer) -> bytes: ...
def urlsafe_b64encode_into(s: ReadableBuffer, output: bytearray) -> int: ...
def urlsafe_b64decode(s: str | ReadableBuffer) -> bytes: ...
def urlsafe_b64decode_into(s: str | ReadableBuffer, output: bytearray) -> int: ...
