from _typeshed import ReadableBuffer

def b64encode(
    s: ReadableBuffer,
    altchars: ReadableBuffer | None = None,
    *,
    padded: bool = True,
    wrapcol: int = 0,
) -> bytes: ...
def b64encode_batch(items: list[ReadableBuffer], altchars: ReadableBuffer | None = None) -> list[bytes]: ...
def b64encode_into(
    s: ReadableBuffer,
    output: bytearray,
    altchars: ReadableBuffer | None = None,
    *,
    padded: bool = True,
    wrapcol: int = 0,
) -> int: ...
def b64decode(
    s: str | ReadableBuffer,
    altchars: str | ReadableBuffer | None = None,
    validate: bool = ...,
    *,
    padded: bool = True,
    ignorechars: ReadableBuffer = ...,
    canonical: bool = False,
) -> bytes: ...
def b64decode_batch(
    items: list[str | ReadableBuffer],
    altchars: str | ReadableBuffer | None = None,
    validate: bool = False,
) -> list[bytes]: ...
def b64decode_into(
    s: str | ReadableBuffer,
    output: bytearray,
    altchars: str | ReadableBuffer | None = None,
    validate: bool = ...,
    *,
    padded: bool = True,
    ignorechars: ReadableBuffer = ...,
    canonical: bool = False,
) -> int: ...
def standard_b64encode(s: ReadableBuffer) -> bytes: ...
def standard_b64encode_batch(items: list[ReadableBuffer]) -> list[bytes]: ...
def standard_b64encode_into(s: ReadableBuffer, output: bytearray) -> int: ...
def standard_b64decode(s: str | ReadableBuffer) -> bytes: ...
def standard_b64decode_batch(items: list[str | ReadableBuffer]) -> list[bytes]: ...
def standard_b64decode_into(s: str | ReadableBuffer, output: bytearray) -> int: ...
def urlsafe_b64encode(s: ReadableBuffer, *, padded: bool = True) -> bytes: ...
def urlsafe_b64encode_batch(items: list[ReadableBuffer]) -> list[bytes]: ...
def urlsafe_b64encode_into(s: ReadableBuffer, output: bytearray, *, padded: bool = True) -> int: ...
def urlsafe_b64decode(s: str | ReadableBuffer, *, padded: bool = ...) -> bytes: ...
def urlsafe_b64decode_batch(items: list[str | ReadableBuffer]) -> list[bytes]: ...
def urlsafe_b64decode_into(s: str | ReadableBuffer, output: bytearray, *, padded: bool = ...) -> int: ...
