from _typeshed import ReadableBuffer

def b64encode(
    s: ReadableBuffer,
    altchars: ReadableBuffer | None = None,
    *,
    padded: bool = True,
    wrapcol: int = 0,
) -> bytes: ...
def b64encode_batch(items: list[ReadableBuffer], altchars: ReadableBuffer | None = None) -> list[bytes]: ...
def b64encode_batch_into(
    items: list[ReadableBuffer],
    outputs: list[bytearray],
    altchars: ReadableBuffer | None = None,
) -> list[int]: ...
def b64encode_into(
    s: ReadableBuffer,
    output: bytearray,
    altchars: ReadableBuffer | None = None,
    *,
    padded: bool = True,
    wrapcol: int = 0,
) -> int: ...
def b64decode(
    s: str | ReadableBuffer,
    altchars: str | ReadableBuffer | None = None,
    validate: bool = ...,
    *,
    padded: bool = True,
    ignorechars: ReadableBuffer = ...,
    canonical: bool = False,
) -> bytes: ...
def b64decode_batch(
    items: list[str | ReadableBuffer],
    altchars: str | ReadableBuffer | None = None,
    validate: bool = False,
) -> list[bytes]: ...
def b64decode_batch_into(
    items: list[str | ReadableBuffer],
    outputs: list[bytearray],
    altchars: str | ReadableBuffer | None = None,
    validate: bool = False,
) -> list[int]: ...
def b64decode_into(
    s: str | ReadableBuffer,
    output: bytearray,
    altchars: str | ReadableBuffer | None = None,
    validate: bool = ...,
    *,
    padded: bool = True,
    ignorechars: ReadableBuffer = ...,
    canonical: bool = False,
) -> int: ...
def standard_b64encode(s: ReadableBuffer) -> bytes: ...
def standard_b64encode_into(s: ReadableBuffer, output: bytearray) -> int: ...
def standard_b64decode(s: str | ReadableBuffer) -> bytes: ...
def standard_b64decode_into(s: str | ReadableBuffer, output: bytearray) -> int: ...
def urlsafe_b64encode(s: ReadableBuffer, *, padded: bool = True) -> bytes: ...
def urlsafe_b64encode_into(s: ReadableBuffer, output: bytearray, *, padded: bool = True) -> int: ...
def urlsafe_b64decode(s: str | ReadableBuffer, *, padded: bool = ...) -> bytes: ...
def urlsafe_b64decode_into(s: str | ReadableBuffer, output: bytearray, *, padded: bool = ...) -> int: ...
def murmur3_32(s: ReadableBuffer, seed: int = 0) -> int: ...
def murmur3_x86_128_digest(s: ReadableBuffer, seed: int = 0) -> bytes: ...
def murmur3_x64_128_digest(s: ReadableBuffer, seed: int = 0) -> bytes: ...
def xxh3_64(s: ReadableBuffer, seed: int = 0) -> int: ...
def xxh3_128(s: ReadableBuffer, seed: int = 0) -> int: ...
def xxh3_64_batch(items: list[ReadableBuffer], seed: int = 0) -> list[int]: ...
def xxh3_64_batch_into(items: list[ReadableBuffer], output: bytearray, seed: int = 0) -> int: ...
def xxh3_128_batch(items: list[ReadableBuffer], seed: int = 0) -> list[int]: ...
def xxh3_128_batch_into(items: list[ReadableBuffer], output: bytearray, seed: int = 0) -> int: ...

class murmur3_x86_32:
    def __init__(self, data: ReadableBuffer | None = None, seed: int = 0) -> None: ...
    def update(self, data: ReadableBuffer) -> None: ...
    def digest(self) -> bytes: ...
    def hexdigest(self) -> str: ...
    def copy(self) -> murmur3_x86_32: ...
    @property
    def digest_size(self) -> int: ...
    @property
    def block_size(self) -> int: ...
    @property
    def name(self) -> str: ...

class murmur3_x86_128:
    def __init__(self, data: ReadableBuffer | None = None, seed: int = 0) -> None: ...
    def update(self, data: ReadableBuffer) -> None: ...
    def digest(self) -> bytes: ...
    def hexdigest(self) -> str: ...
    def copy(self) -> murmur3_x86_128: ...
    @property
    def digest_size(self) -> int: ...
    @property
    def block_size(self) -> int: ...
    @property
    def name(self) -> str: ...

class murmur3_x64_128:
    def __init__(self, data: ReadableBuffer | None = None, seed: int = 0) -> None: ...
    def update(self, data: ReadableBuffer) -> None: ...
    def digest(self) -> bytes: ...
    def hexdigest(self) -> str: ...
    def copy(self) -> murmur3_x64_128: ...
    @property
    def digest_size(self) -> int: ...
    @property
    def block_size(self) -> int: ...
    @property
    def name(self) -> str: ...
