"""A fast, API-compatible subset of Python's :mod:`base64` module."""

from ._hashcodecs import (
    b64decode,
    b64decode_batch,
    b64decode_batch_into,
    b64decode_into,
    b64encode,
    b64encode_batch,
    b64encode_batch_into,
    b64encode_into,
    standard_b64decode,
    standard_b64decode_batch,
    standard_b64decode_batch_into,
    standard_b64decode_into,
    standard_b64encode,
    standard_b64encode_batch,
    standard_b64encode_batch_into,
    standard_b64encode_into,
    urlsafe_b64decode,
    urlsafe_b64decode_batch,
    urlsafe_b64decode_batch_into,
    urlsafe_b64decode_into,
    urlsafe_b64encode,
    urlsafe_b64encode_batch,
    urlsafe_b64encode_batch_into,
    urlsafe_b64encode_into,
)

for _function in (
    b64decode,
    b64decode_batch,
    b64decode_batch_into,
    b64decode_into,
    b64encode,
    b64encode_batch,
    b64encode_batch_into,
    b64encode_into,
    standard_b64decode,
    standard_b64decode_batch,
    standard_b64decode_batch_into,
    standard_b64decode_into,
    standard_b64encode,
    standard_b64encode_batch,
    standard_b64encode_batch_into,
    standard_b64encode_into,
    urlsafe_b64decode,
    urlsafe_b64decode_batch,
    urlsafe_b64decode_batch_into,
    urlsafe_b64decode_into,
    urlsafe_b64encode,
    urlsafe_b64encode_batch,
    urlsafe_b64encode_batch_into,
    urlsafe_b64encode_into,
):
    _function.__module__ = __name__
del _function


__all__ = [
    'b64decode',
    'b64decode_batch',
    'b64decode_batch_into',
    'b64decode_into',
    'b64encode',
    'b64encode_batch',
    'b64encode_batch_into',
    'b64encode_into',
    'standard_b64decode',
    'standard_b64decode_batch',
    'standard_b64decode_batch_into',
    'standard_b64decode_into',
    'standard_b64encode',
    'standard_b64encode_batch',
    'standard_b64encode_batch_into',
    'standard_b64encode_into',
    'urlsafe_b64decode',
    'urlsafe_b64decode_batch',
    'urlsafe_b64decode_batch_into',
    'urlsafe_b64decode_into',
    'urlsafe_b64encode',
    'urlsafe_b64encode_batch',
    'urlsafe_b64encode_batch_into',
    'urlsafe_b64encode_into',
]
