"""Generate Python and native API metadata from the typed extension stub."""

from __future__ import annotations

import argparse
import ast
import re
import sys
import textwrap
from collections.abc import Iterable
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
STUB = ROOT / 'hashcodecs' / '_hashcodecs.pyi'

MODULES = ('base64', 'murmur3', 'xxhash')
MODULE_DOCSTRINGS = {
    'base64': "A fast, API-compatible subset of Python's :mod:`base64` module.",
    'murmur3': 'Fast one-shot and incremental MurmurHash3 functions.',
    'xxhash': 'Fast, canonical XXH3 hashes.',
}
API_TITLES = {
    'base64': 'Base64 API Reference',
    'murmur3': 'MurmurHash3 API Reference',
    'xxhash': 'XXH3 API Reference',
}
API_FILENAMES = {'base64': 'base64.md', 'murmur3': 'murmur3.md', 'xxhash': 'xxh3.md'}
API_INTRODUCTIONS = {
    'base64': (
        'The functions below are rendered from the authoritative typed API declaration. '
        'They describe the exact call signatures and behavior exposed by `hashcodecs.base64`.'
    ),
    'murmur3': (
        'The functions and incremental hashers below are rendered from the authoritative typed API declaration.'
    ),
    'xxhash': 'The functions below are rendered from the authoritative typed API declaration.',
}
METHOD_FILES = {
    'base64': ROOT / 'src' / 'bindings' / 'base64' / 'methods.rs',
    'murmur3': ROOT / 'src' / 'bindings' / 'murmur3' / 'methods.rs',
    'xxhash': ROOT / 'src' / 'bindings' / 'xxhash' / 'methods.rs',
}
GENERATED_HEADER = '# Generated by tools/generate_api_metadata.py from hashcodecs/_hashcodecs.pyi.\n'
METHOD_DOC_PATTERN = re.compile(
    r'ml_doc:\s+cr(?P<hashes>\#*)"(?P<body>.*?)"(?P=hashes)\s*\.as_ptr\(\),',
    re.DOTALL,
)


def module_for(name: str) -> str:
    if 'b64' in name:
        return 'base64'
    if name.startswith('murmur3_'):
        return 'murmur3'
    if name.startswith('xxh3_'):
        return 'xxhash'
    raise ValueError(f'cannot assign public API name {name!r} to a module')


def declarations() -> dict[str, list[ast.FunctionDef | ast.ClassDef]]:
    tree = ast.parse(STUB.read_text(encoding='utf-8'), filename=str(STUB))
    grouped = {module: [] for module in MODULES}
    for node in tree.body:
        if isinstance(node, (ast.FunctionDef, ast.ClassDef)) and not node.name.startswith('_'):
            grouped[module_for(node.name)].append(node)
    return grouped


def format_names(names: Iterable[str], indent: str = '    ') -> str:
    return ''.join(f'{indent}{name},\n' for name in names)


def format_string_names(names: Iterable[str], indent: str = '    ') -> str:
    return ''.join(f"{indent}'{name}',\n" for name in names)


def natural_key(name: str) -> tuple[str | int, ...]:
    return tuple(int(part) if part.isdigit() else part for part in re.split(r'(\d+)', name))


def render_runtime_module(module: str, names: list[str]) -> str:
    return (
        f'{GENERATED_HEADER}"""{MODULE_DOCSTRINGS[module]}"""\n\n'
        'from ._hashcodecs import (\n'
        f'{format_names(names)})\n\n'
        'for _public_api in (\n'
        f'{format_names(names)}):\n'
        '    _public_api.__module__ = __name__\n'
        'del _public_api\n\n'
        '__all__ = [\n'
        f'{format_string_names(names)}]\n'
    )


def render_root_module(grouped_names: dict[str, list[str]]) -> str:
    imports = ''.join(f'from .{module} import (\n{format_names(names)})\n' for module, names in grouped_names.items())
    all_names = sorted((name for names in grouped_names.values() for name in names), key=natural_key)
    return (
        f'{GENERATED_HEADER}"""SIMD-accelerated Base64, MurmurHash3, and XXH3 functions."""\n\n'
        f'{imports}\n'
        '__all__ = [\n'
        f'{format_string_names(all_names)}]\n'
    )


def render_stub(import_module: str, names: list[str]) -> str:
    imports = ''.join(f'from .{import_module} import {name} as {name}\n' for name in names)
    return f'{GENERATED_HEADER}{imports}\n__all__ = [\n{format_string_names(names)}]\n'


def render_api_reference(module: str, names: list[str]) -> str:
    members = ''.join(f'        - {name}\n' for name in names)
    introduction = textwrap.fill(API_INTRODUCTIONS[module], width=119)
    return (
        f'# {API_TITLES[module]}\n\n'
        f'{introduction}\n\n'
        '::: hashcodecs._hashcodecs\n'
        '    options:\n'
        '      members:\n'
        f'{members}'
        '      show_root_heading: false\n'
    )


def render_default(value: ast.expr | None, function: str, argument: str, *, python_315: bool) -> str | None:
    if value is None:
        return None
    if isinstance(value, ast.Constant) and value.value is Ellipsis:
        if function in {'urlsafe_b64decode', 'urlsafe_b64decode_into'} and argument == 'padded':
            return 'False' if python_315 else 'True'
        return "['NOT SPECIFIED']"
    return ast.unparse(value)


def text_signature(function: ast.FunctionDef, *, python_315: bool = False) -> str:
    positional = [*function.args.posonlyargs, *function.args.args]
    positional_defaults = [None] * (len(positional) - len(function.args.defaults)) + list(function.args.defaults)
    rendered = []
    for argument, default in zip(positional, positional_defaults, strict=True):
        value = render_default(default, function.name, argument.arg, python_315=python_315)
        rendered.append(argument.arg if value is None else f'{argument.arg}={value}')
    if function.args.kwonlyargs:
        rendered.append('*')
        for argument, default in zip(function.args.kwonlyargs, function.args.kw_defaults, strict=True):
            value = render_default(default, function.name, argument.arg, python_315=python_315)
            rendered.append(argument.arg if value is None else f'{argument.arg}={value}')
    arguments = ', '.join(rendered)
    return f'{function.name}($module, /, {arguments})'


def runtime_doc(function: ast.FunctionDef, *, python_315: bool = False) -> str:
    docstring = ast.get_docstring(function, clean=True)
    if not docstring:
        raise ValueError(f'{function.name} has no API docstring')
    return f'{text_signature(function, python_315=python_315)}\n--\n\n{docstring}'


def render_method_file(path: Path, functions: dict[str, ast.FunctionDef]) -> str:
    source = path.read_text(encoding='utf-8')
    method_names = re.findall(r'ml_name:\s+c"([^"]+)"', source)
    if len(method_names) != len(set(method_names)) or set(method_names) != set(functions):
        raise ValueError(f'{path}: native method names {method_names!r} do not match the typed declarations')
    seen: dict[str, int] = {}

    def replace(match: re.Match[str]) -> str:
        first_line = match.group('body').splitlines()[0]
        name = first_line.split('(', 1)[0]
        function = functions.get(name)
        if function is None:
            raise ValueError(f'{path}: native method {name!r} is absent from {STUB.name}')
        occurrence = seen.get(name, 0)
        seen[name] = occurrence + 1
        python_315 = occurrence > 0 and name in {'urlsafe_b64decode', 'urlsafe_b64decode_into'}
        return f'ml_doc: cr###"{runtime_doc(function, python_315=python_315)}"###.as_ptr(),'

    rendered = METHOD_DOC_PATTERN.sub(replace, source)
    expected = set(functions)
    missing = expected - seen.keys()
    if missing:
        raise ValueError(f'{path}: native method table is missing {sorted(missing)}')
    return rendered


def generated_files() -> dict[Path, str]:
    grouped = declarations()
    grouped_names = {
        module: sorted((node.name for node in nodes), key=natural_key) for module, nodes in grouped.items()
    }
    outputs: dict[Path, str] = {}
    for module, names in grouped_names.items():
        outputs[ROOT / 'hashcodecs' / f'{module}.py'] = render_runtime_module(module, names)
        outputs[ROOT / 'hashcodecs' / f'{module}.pyi'] = render_stub('_hashcodecs', names)
        outputs[ROOT / 'docs' / 'api' / API_FILENAMES[module]] = render_api_reference(module, names)
    outputs[ROOT / 'hashcodecs' / '__init__.py'] = render_root_module(grouped_names)
    outputs[ROOT / 'hashcodecs' / '__init__.pyi'] = render_stub(
        '_hashcodecs', sorted((name for names in grouped_names.values() for name in names), key=natural_key)
    )

    for module, path in METHOD_FILES.items():
        functions = {node.name: node for node in grouped[module] if isinstance(node, ast.FunctionDef)}
        outputs[path] = render_method_file(path, functions)
    return outputs


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument('--check', action='store_true', help='fail when generated files are stale')
    args = parser.parse_args()

    stale = []
    for path, content in generated_files().items():
        if path.exists():
            current = path.read_text(encoding='utf-8')
            if path in METHOD_FILES.values():
                current = re.sub(r'"###\s*\.as_ptr\(\)', '"###.as_ptr()', current)
                content = re.sub(r'"###\s*\.as_ptr\(\)', '"###.as_ptr()', content)
            if current == content:
                continue
        stale.append(path.relative_to(ROOT))
        if not args.check:
            path.write_text(content, encoding='utf-8', newline='')

    if stale and args.check:
        print('Generated API metadata is stale:', file=sys.stderr)
        for path in stale:
            print(f'  {path}', file=sys.stderr)
        print('Run: python tools/generate_api_metadata.py', file=sys.stderr)
        return 1
    if stale:
        print(f'Updated {len(stale)} generated API files.')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
